// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0

package queries

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Url struct {
	ID        int32
	Url       string
	Slug      string
	CreatedAt pgtype.Timestamp
}
